"""
voucher-generator entrypoint.

Scope: sales.sales (+ sale_items, order, party) in -> one sales.invoices row
out per sale, with a PDF generated by the pdfservice and stored on Drive.
Does not touch orders/sales/sale_items/inventory -- those belong to the
processes that write them. Every eligible sale gets invoiced regardless of
the order's bill_whatsapp flag; voucher-sender (separate, downstream)
decides whether to also push a copy to WhatsApp.

Cron-shaped, not a webhook -- meant to be triggered on a schedule (e.g. a
Render Cron Job, nightly per the agreed run-flow), not run as a persistent
service. Each run processes every currently-unbilled sale and exits.

One sale's failure (unknown SKU, unmapped line_type, pdfservice error) does
NOT abort the run -- it's recorded in `failed` and the run continues with
the next sale, so one bad record doesn't block invoicing for everyone else.
"""

from db import get_client, fetch_unbilled_sales, insert_invoice
from invoice_builder import build_invoice_request, UninvoiceableLineTypeError
from invoice_catalog import UnknownSkuForInvoiceError
from invoice_numbering import get_next_invoice_number
from pdfservice_client import generate_invoice_pdf, PdfServiceError


def run_once() -> dict:
    client = get_client()
    records = fetch_unbilled_sales(client)

    if not records:
        return {"invoiced_count": 0, "failed_count": 0, "message": "nothing to invoice"}

    invoiced = []
    failed = []

    for record in records:
        sale_id = record["sale"]["id"]
        try:
            invoice_number = get_next_invoice_number(client)
            payload = build_invoice_request(record, invoice_number)
            pdf_result = generate_invoice_pdf(payload)
            invoice_row = insert_invoice(
                client,
                sale_id=sale_id,
                invoice_number=invoice_number,
                invoice_date=payload["invoiceDate"],
                file_url=pdf_result["fileUrl"],
                drive_file_id=pdf_result["driveFileId"],
            )
            invoiced.append({"sale_id": sale_id, "invoice_number": invoice_number, "invoice_id": invoice_row["id"], "file_url": pdf_result["fileUrl"]})
        except (UnknownSkuForInvoiceError, UninvoiceableLineTypeError, PdfServiceError) as e:
            failed.append({"sale_id": sale_id, "reason": str(e)})

    return {
        "invoiced_count": len(invoiced),
        "invoiced": invoiced,
        "failed_count": len(failed),
        "failed": failed,
    }


if __name__ == "__main__":
    result = run_once()
    print(result)
